// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiCopierWPF.Data;

#nullable disable

namespace MultiCopierWPF.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    [Migration("20250430172335_AddLastModifiedProperty")]
    partial class AddLastModifiedProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MultiCopierWPF.Models.BackupEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BackupTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedFilePath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptionKey")
                        .HasColumnType("BLOB");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("IV")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SHA512")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("BackupEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
